cards = [
{ "number": 1, "name": "Alakazam" },
    { "number": 2, "name": "Blastoise" },
    { "number": 3, "name": "Chansey" },
    { "number": 4, "name": "Charizard" },
    { "number": 5, "name": "Clefairy" },
    { "number": 6, "name": "Gyarados" },
    { "number": 7, "name": "Hitmonchan" },
    { "number": 8, "name": "Machamp" },
    { "number": 9, "name": "Magneton" },
    { "number": 10, "name": "Mewtwo" },
    { "number": 11, "name": "Nidoking" },
    { "number": 12, "name": "Ninetales" },
    { "number": 13, "name": "Poliwrath" },
    { "number": 14, "name": "Raichu" },
    { "number": 15, "name": "Venusaur" },
    { "number": 16, "name": "Zapdos" },
    { "number": 17, "name": "Beedrill" },
    { "number": 18, "name": "Dragonair" },
    { "number": 19, "name": "Dugtrio" },
    { "number": 20, "name": "Electabuzz" },
    { "number": 21, "name": "Electrode" },
    { "number": 22, "name": "Pidgeotto" },
    { "number": 23, "name": "Arcanine" },
    { "number": 24, "name": "Charmeleon" },
    { "number": 25, "name": "Dewgong" },
    { "number": 26, "name": "Dratini" },
    { "number": 27, "name": "Farfetch'd" },
    { "number": 28, "name": "Growlithe" },
    { "number": 29, "name": "Haunter" },
    { "number": 30, "name": "Ivysaur" },
    { "number": 31, "name": "Jynx" },
    { "number": 32, "name": "Kadabra" },
    { "number": 33, "name": "Kakuna" },
    { "number": 34, "name": "Machoke" },
    { "number": 35, "name": "Magikarp" },
    { "number": 36, "name": "Magmar" },
    { "number": 37, "name": "Nidorino" },
    { "number": 38, "name": "Poliwhirl" },
    { "number": 39, "name": "Porygon" },
    { "number": 40, "name": "Raticate" },
    { "number": 41, "name": "Seel" },
    { "number": 42, "name": "Wartortle" },
    { "number": 43, "name": "Abra" },
    { "number": 44, "name": "Bulbasaur" },
    { "number": 45, "name": "Caterpie" },
    { "number": 46, "name": "Charmander" },
    { "number": 47, "name": "Diglett" },
    { "number": 48, "name": "Doduo" },
    { "number": 49, "name": "Drowzee" },
    { "number": 50, "name": "Gastly" },
    { "number": 51, "name": "Koffing" },
    { "number": 52, "name": "Machop" },
    { "number": 53, "name": "Magnemite" },
    { "number": 54, "name": "Metapod" },
    { "number": 55, "name": "Nidoran" },
    { "number": 56, "name": "Onix" },
    { "number": 57, "name": "Pidgey" },
    { "number": 58, "name": "Pikachu" },
    { "number": 59, "name": "Poliwag" },
    { "number": 60, "name": "Ponyta" },
    { "number": 61, "name": "Rattata" },
    { "number": 62, "name": "Sandshrew" },
    { "number": 63, "name": "Squirtle" },
    { "number": 64, "name": "Starmie" },
    { "number": 65, "name": "Staryu" },
    { "number": 66, "name": "Tangela" },
    { "number": 67, "name": "Voltorb" },
    { "number": 68, "name": "Vulpix" },
    { "number": 69, "name": "Weedle" },
    { "number": 70, "name": "Clefairy Doll" },
    { "number": 71, "name": "Computer Search" },
    { "number": 72, "name": "Devolution Spray" },
    { "number": 73, "name": "Imposter Professor Oak" },
    { "number": 74, "name": "Item Finder" },
    { "number": 75, "name": "Lass" },
    { "number": 76, "name": "Pokemon Breeder" },
    { "number": 77, "name": "Pokemon Trader" },
    { "number": 78, "name": "Scoop Up" },
    { "number": 79, "name": "Super Energy Removal" },
    { "number": 80, "name": "Defender" },
    { "number": 81, "name": "Energy Retrieval" },
    { "number": 82, "name": "Full Heal" },
    { "number": 83, "name": "Maintenance" },
    { "number": 84, "name": "PlusPower" },
    { "number": 85, "name": "Pokemon Center" },
    { "number": 86, "name": "Pokemon Flute" },
    { "number": 87, "name": "Pokedex" },
    { "number": 88, "name": "Professor Oak" },
    { "number": 89, "name": "Revive" },
    { "number": 90, "name": "Super Potion" },
    { "number": 91, "name": "Bill" },
    { "number": 92, "name": "Energy Removal" },
    { "number": 93, "name": "Gust of Wind" },
    { "number": 94, "name": "Potion" },
    { "number": 95, "name": "Switch" },
    { "number": 96, "name": "Double Colorless Energy" },
    { "number": 97, "name": "Fighting Energy" },
    { "number": 98, "name": "Fire Energy" },
    { "number": 99, "name": "Grass Energy" },
    { "number": 100, "name": "Lightning Energy" },
    { "number": 101, "name": "Psychic Energy" },
    { "number": 102, "name": "Water Energy" },
  ]